name: marlo
channels:
  - crowdai
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.6
  - ca-certificates=2018.8.24
  - certifi=2018.8.24
  - libffi=3.2.1
  - libgcc-ng=7.2.0
  - libstdcxx-ng=7.2.0
  - ncurses=6.1
  - openssl=1.0.2p
  - pip=18.0
  - python=3.6.6
  - readline=7.0
  - setuptools=40.4.0
  - sqlite=3.25.1
  - tk=8.6.8
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
  - malmo=0.36.0
  - openjdk=8.0.152
  - pip:
    - chardet==3.0.4
    - crowdai-api==0.1.17
    - future==0.16.0
    - gym==0.10.5
    - idna==2.7
    - jinja2==2.10
    - lxml==4.2.5
    - markupsafe==1.0
    - marlo==0.0.1.dev16
    - numpy==1.15.2
    - pyglet==1.3.2
    - python-gitlab==1.6.0
    - redis==2.10.6
    - requests==2.19.1
    - six==1.11.0
    - urllib3==1.23
prefix: /home/mohanty/anaconda3/envs/marlo

